#!/usr/bin/env ruby

require 'json'
require 'net/https'
require 'uri'

def source_env_from(file)
  File.readlines(file).each do |line|
    values = line.chomp.split("=")
    ENV[values[0]] = values[1]
  end
end

def validate
  raise "You must provide a url" if ENV['PLUGIN_URL'].nil?
  raise "You must provide a status" if ENV['PLUGIN_STATUS'].nil?
end

def json
  j = {'status' => ENV['PLUGIN_STATUS']}
  j['subject'] = ENV['PLUGIN_SUBJECT'] unless ENV['PLUGIN_SUBJECT'].nil?
  j['color'] = ENV['PLUGIN_COLOR'] unless ENV['PLUGIN_COLOR'].nil?
  j.to_json
end

source_env_from('.badges') if File.exist?('.badges')
validate

if ENV['PLUGIN_DEBUG'] == 'true'
  puts "json: #{json}"
end

header = {'Content-Type': 'application/json'}
uri = URI.parse(ENV['PLUGIN_URL'])

# Create the HTTP objects
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
request = Net::HTTP::Put.new(uri.request_uri, header)
request.body = json

puts "Posting data to #{ENV['PLUGIN_URL']}"
begin
  response = http.request(request)
rescue Exception => e
  puts e.message
  puts e.backtrace.inspect
end
